### ISSUE TITLE
Can't press play

### ISSUE THREAD

**Issue by SaberShock** [ParadoxGameConverters/frontend#8]
So, this is likely just user error, but I'm new to this whole thing. My apologies if you've addressed this before, but I couldn't find anything. Heck. I'm not even sure if this was the right place to bring this up. I'm really sorry. Anyway, the problem I'm having is 2 fold. So first, I can't convert any save that wasn't autosaved at the end date. It pops up with a message about renaming the file. Second, and this is the most troubling to be honest, if I do get the files to convert, it doesn't actually let me play them in Vic2. It loads fine. It gets to the choose your nation map just fine. The map clearly shows the world as I saved it in EU4. However, the play button on the bottom left stays gray no matter how many times I click. Any idea what I'm doing wrong here?

**Comment by Idhrendur** [comment]
Maybe? I'm not sure if they generate ISO 8859-15 code points, UTF-8 code points, or UCS-2 code points. Or for that matter, which of those possible sets are causing problems.
